# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicregion',
            options={'ordering': ('region_nam',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',), 'verbose_name': 'Language'},
        ),
        migrations.AlterModelOptions(
            name='languagefamily',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='languagetree',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'ordering': ('name',), 'verbose_name_plural': 'Societies'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ('label',), 'verbose_name': 'Variable'},
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='continent',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='geographicregion',
            name='region_nam',
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
