# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-02 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalvalue',
            name='value',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
