# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ext_id',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='society',
            name='xd_id',
            field=models.CharField(db_index=True, default=None, max_length=10, null=True, verbose_name='Cross ID'),
        ),
        migrations.AlterField(
            model_name='source',
            name='author',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='year',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
