# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0002_auto_20160502_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalvalue',
            name='value',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='environmentalvariable',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
