# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0003_auto_20170310_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalvariable',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
