# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='original_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='ORIG_name'),
        ),
    ]
