# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0076_society_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='ext_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='External ID'),
        ),
    ]
