# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0076_society_original_name'),
        ('dplace_app', '0077_increase_max_length_for_Society_id'),
        ('dplace_app', '0002_add_indexes'),
    ]

    operations = [
    ]
