# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0078_update_cultural_value_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalvariable',
            name='units',
            field=models.CharField(choices=[('mm', 'mm'), ('\u2103', '\u2103'), ('mo', 'mo'), ('', ''), ('gC m-2 day-1', 'gC m-2 day-1')], max_length=100),
        ),
    ]
