# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0079_increase_max_length_for_env_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalvalue',
            name='coded_value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='ext_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='External ID'),
        ),
    ]
