# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0080_auto_20160311_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='chirila_link',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='CHIRILA'),
        ),
        migrations.AddField(
            model_name='society',
            name='hraf_link',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='HRAF'),
        ),
    ]
