# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0083_original_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalvalue',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
