# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dplace_app', '0085_add_field_varid_to_environmentalvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalvariable',
            name='units',
            field=models.CharField(default='', max_length=100),
        ),
    ]
